language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt511
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake qt51base qt51quickcontrols libopencv-dev libopencv-core2.3  libopencv-core-dev libopencv-highgui2.3 libopencv-highgui-dev libopencv-flann-dev libopencv-flann2.3 libopencv-features2d2.3 libopencv-features2d-dev libmagic1 libmagic-dev
before_script:
  - source /opt/qt51/bin/qt51-env.sh
  - cd src
  - cmake -DALGORITHMS='adjuster' .
script:
  - make

