language: cpp
compiler:
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt511
  - sudo add-apt-repository --yes ppa:limparissoft/opencv-ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake qt51base qt51quickcontrols opencv libmagic1 libmagic-dev openscenegraph libopenscenegraph-dev
before_script:
  - source /opt/qt51/bin/qt51-env.sh
  - cd src
  - cmake -DALGORITHMS='adjuster' .
script:
  - make
after_script:
  - ls -lah arstudio
  - ldd arstudio
