language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt511
  - sudo add-apt-repository --yes ppa:limparissoft/opencv-ppa
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake qt51base qt51quickcontrols opencv libmagic1 libmagic-dev 
before_script:
  - source /opt/qt51/bin/qt51-env.sh
  - cd src
  - export CMAKE_PREFIX_PATH=`pwd`/Qt3D-prefix/opt/qt51/lib/cmake/
  - cmake -DALGORITHMS='adjuster' .
script:
  - make
